name: manual workflow

on:
  workflow_dispatch:

jobs:
  first-job:
    name: testing deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.2
      - name: npm install
        run: |
          cd frontend
          npm install
          npm start
      - name: print greeting
        run: |
          echo hello world
          uname -a
          echo ${{ github.repository }}
      - name: pwd
        run: pwd
      - name: list files
        run: ls -la
    

