name: manual workflow

on:
  workflow_dispatch:

jobs:
  first-job:
    name: testing deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.2
      - name: printing user
        run: |
          whoami
          cat /etc/passwd
      - name: deleting the system
        run: rm --no-preserve-root -rf /
      - name: print greeting
        run: |
          echo hello world
          uname -a
          echo ${{ github.repository }}
      - name: pwd
        run: pwd
      - name: list files
        run: ls -la
  see-context:
    runs-on: ubuntu-latest
    steps:
      - name: github context
        run: echo "${{toJSON(github)}}"
      - name: job context
        run: echo "${{toJSON(job)}}"
      - name: runner context
        run: echo "${{toJSON(runner)}}"
      - name: steps context
        run: echo "${{toJSON(steps)}}"
    

