name: manual workflow

on:
  workflow_dispatch:

jobs:
  first-job:
    name: testing deploy
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: |
          echo hello world
          uname -a
    

